### Merge mosquito data (tested and not tested) to town shapefile

In [28]:
import pandas as pd
import geopandas as gpd
from matplotlib import pyplot
from shapely.geometry import LineString
from descartes import PolygonPatch

In [29]:
gdf = gpd.read_file("/Users/lbrown01/Dropbox/DataScienceStuff/Data/RasterShapefiles/townssurvey_shp/TOWNSSURVEY_POLY.shp")

In [30]:
gdf.describe()

,TOWN_ID,POP1980,POP1990,POP2000,POPCH80_90,POPCH90_00,ISLAND,FOURCOLOR,FIPS_STCO,FIPS_MCD,FIPS_COUNT,ACRES,SQUARE_MIL,POP2010,POPCH00_10,SHAPE_Leng,SHAPE_Area
count,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1.243000e+03,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1.243000e+03
mean,168.904264,28833.148029,29742.781175,31372.786002,909.633146,1630.004827,0.593725,2.456154,25011.432824,2.501156e+07,11.432824,4169.280083,6.514488,32367.342719,994.556718,13441.021167,1.684947e+07
std,97.287849,82953.806500,83540.039333,85586.655971,1682.711559,2678.956332,0.491335,1.140091,8.434418,8.469394e+03,8.434418,7852.842582,12.269995,89694.594245,4313.410104,22056.972877,3.178475e+07
min,1.000000,58.000000,98.000000,86.000000,-3104.000000,-6348.000000,0.000000,1.000000,25001.000000,2.500100e+07,1.000000,0.002000,0.000000,75.000000,-3081.000000,14.921290,8.529000e+00
25%,87.500000,4691.000000,5286.000000,5904.500000,40.000000,256.000000,0.000000,1.000000,25005.000000,2.500507e+07,5.000000,0.739500,0.001000,5890.000000,-245.000000,281.160335,3.021172e+03
50%,160.000000,11566.000000,11873.000000,12987.000000,329.000000,945.000000,1.000000,2.000000,25009.000000,2.500911e+07,9.000000,5.503000,0.009000,13794.000000,201.000000,868.568025,2.168062e+04
75%,248.000000,24556.000000,25549.000000,26078.000000,751.000000,1872.000000,1.000000,3.000000,25021.000000,2.502102e+07,21.000000,6262.005000,9.784500,26993.000000,1020.000000,26399.879787,2.534144e+07
max,351.000000,570719.000000,574283.000000,588957.000000,9966.000000,14674.000000,1.000000,4.000000,25027.000000,2.502737e+07,27.000000,65290.148000,102.015000,617594.000000,28637.000000,191229.569256,2.642198e+08

In [31]:
gdf.shape

(1243, 23)

In [32]:
#there are 351 towns but 1243 rows, check duplicates
gdf.TOWN_ID.nunique()

351

In [33]:
gdf.TOWN.nunique()

351

In [34]:
#check duplicate town rows
#gdf[gdf.duplicated(['TOWN_ID'],keep=False)] 
gdf.sort_values(by=['TOWN_ID'])

,TOWN,TOWN_ID,POP1980,POP1990,POP2000,POPCH80_90,POPCH90_00,TYPE,ISLAND,COASTAL_PO,...,FIPS_PLACE,FIPS_MCD,FIPS_COUNT,ACRES,SQUARE_MIL,POP2010,POPCH00_10,SHAPE_Leng,SHAPE_Area,geometry
542,ABINGTON,1,13579,13817,14605,238,788,T,0,NO,...,00170,25023005,23,6521.335,10.190,15985,1380,24139.413120,2.639085e+07,"POLYGON ((248314.4724999964 872355.4946000017,..."
747,ACTON,2,17672,17872,20331,200,2459,T,0,NO,...,00380,25017005,17,12988.988,20.295,21924,1593,30789.187913,5.256453e+07,"POLYGON ((209456.3725000024 917108.8746000007,..."
1072,ACUSHNET,3,8808,9554,10161,746,607,T,0,NO,...,00520,25005005,5,12081.818,18.878,10303,142,31637.669325,4.889337e+07,"POLYGON ((252855.8524999991 827963.5945999995,..."
1170,ADAMS,4,10181,9445,8809,-736,-636,T,0,NO,...,00555,25003005,3,14694.491,22.960,8485,-324,31135.753626,5.946649e+07,"POLYGON ((71824.76250000298 934966.1345999986,..."
1193,AGAWAM,5,26754,27323,28144,569,821,TC,0,NO,...,00800,25013005,13,15574.332,24.335,28438,294,38060.713034,6.302191e+07,"POLYGON ((102185.3125 873555.6645999998, 10218..."
255,ALFORD,6,402,418,399,16,-19,T,0,NO,...,00975,25003010,3,7381.318,11.533,494,95,25353.440653,2.987113e+07,"POLYGON ((43038.84250000119 891536.3746000007,..."
719,AMESBURY,7,14563,14997,16450,434,1453,C,0,NO,...,01185,25009005,9,8432.073,13.175,16283,-167,33529.271758,3.412335e+07,"POLYGON ((248808.3924999982 954289.6246000007,..."
345,AMESBURY,7,14563,14997,16450,434,1453,C,1,NO,...,01185,25009005,9,0.254,0.000,16283,-167,123.427303,1.027833e+03,"POLYGON ((248015.262500003 954365.9246000014, ..."
717,AMESBURY,7,14563,14997,16450,434,1453,C,1,NO,...,01185,25009005,9,7.441,0.012,16283,-167,789.369822,3.011371e+04,"POLYGON ((248731.4025000036 953963.6246000007,..."
1009,AMESBURY,7,14563,14997,16450,434,1453,C,0,YES,...,01185,25009005,9,344.139,0.538,16283,-167,23235.762568,1.392675e+06,"POLYGON ((247963.6724999994 954624.6246000007,..."
1236,AMHERST,8,32804,35228,34874,2424,-354,T,0,NO,...,01325,25015005,15,17762.606,27.754,37819,2945,40766.344847,7.188264e+07,"POLYGON ((119026.9224999994 906796.5645999983,..."
1101,ANDOVER,9,27203,29151,31247,1948,2096,T,0,NO,...,01465,25009010,9,20368.848,31.826,33201,1954,47921.464315,8.242976e+07,"POLYGON ((225513.2025000006 938332.1246000007,..."
821,ANDOVER,9,27203,29151,31247,1948,2096,T,0,YES,...,01465,25009010,9,1.573,0.003,33201,1954,528.081801,6.365173e+03,"POLYGON ((225517.0424999967 938305.4345999993,..."
1083,ANDOVER,9,27203,29151,31247,1948,2096,T,0,YES,...,01465,25009010,9,207.189,0.324,33201,1954,18518.700347,8.384623e+05,"POLYGON ((225495.5024999976 938455.0045999996,..."
1089,ARLINGTON,10,45640,44630,42389,-1010,-2241,T,0,YES,...,01605,25017010,17,113.697,0.178,42844,455,12009.575548,4.601161e+05,"POLYGON ((228920.4624999985 908971.0146000013,..."
1227,ARLINGTON,10,45640,44630,42389,-1010,-2241,T,0,NO,...,01605,25017010,17,3396.175,5.307,42844,455,17507.261012,1.374382e+07,"POLYGON ((228788.1525000036 908964.9946000017,..."
606,ASHBURNHAM,11,4406,5433,5546,1027,113,T,0,NO,...,01885,25027005,27,26208.922,40.951,6081,535,41818.021136,1.060637e+08,"POLYGON ((167331.9224999994 940156.2146000005,..."
633,ASHBY,12,2562,2717,2845,155,128,T,0,NO,...,01955,25017015,17,15406.763,24.073,3074,229,35422.495853,6.234896e+07,"POLYGON ((177670.9525000006 939762.2346000001,..."
1052,ASHFIELD,13,1502,1715,1800,213,85,T,0,NO,...,02095,25011005,11,25776.385,40.275,1737,-63,41119.406245,1.042296e+08,"POLYGON ((97736.96249999851 924492.7545999996,..."
891,ASHLAND,14,10328,12066,14674,1738,2608,T,0,NO,...,02130,25017020,17,8239.158,12.874,16593,1919,25926.517980,3.334268e+07,"POLYGON ((206658.9425000027 889649.2245999984,..."
1080,ATHOL,15,10560,11451,11299,891,-152,T,0,NO,...,02480,25027010,27,21352.105,33.362,11584,285,48172.897625,8.640883e+07,"POLYGON ((146318.4324999973 930568.8046000004,..."
303,ATTLEBORO,16,33861,38383,42068,4522,3685,C,0,NO,...,02690,25005210,5,17773.159,27.770,43593,1525,39370.231118,7.192543e+07,"POLYGON ((219949.1824999973 858232.3845999986,..."
37,AUBURN,17,14477,15005,15901,528,896,T,0,NO,...,02760,25027015,27,10505.170,16.414,16188,287,24816.995407,4.251297e+07,"POLYGON ((175463.7524999976 884441.4646000005,..."
339,AVON,18,4843,4558,4443,-285,-115,T,0,NO,...,02935,25021005,21,2904.519,4.538,4356,-87,14934.241555,1.175418e+07,"POLYGON ((238434.6625000015 876239.4045999981,..."
705,AYER,19,6637,6871,7287,234,416,T,0,NO,...,03005,25017025,17,6082.089,9.503,7427,140,25016.907017,2.461333e+07,"POLYGON ((191765.7424999997 925823.1545999981,..."
246,BARNSTABLE,20,35080,40949,47821,5869,6872,TC,1,NO,...,03635,25001005,1,4.935,0.008,45193,-2628,657.372930,1.997265e+04,"POLYGON ((295061.4724999964 831599.9345999993,..."
947,BARNSTABLE,20,35080,40949,47821,5869,6872,TC,0,NO,...,03635,25001005,1,0.826,0.001,45193,-2628,267.354416,3.342119e+03,"POLYGON ((302107.0525000021 822664.1746000014,..."
769,BARNSTABLE,20,35080,40949,47821,5869,6872,TC,1,NO,...,03635,25001005,1,0.349,0.001,45193,-2628,145.392804,1.413707e+03,"POLYGON ((298701.1824999973 832405.0045999996,..."
138,BARNSTABLE,20,35080,40949,47821,5869,6872,TC,1,NO,...,03635,25001005,1,1.402,0.002,45193,-2628,317.602502,5.674101e+03,"POLYGON ((297854.9425000027 831089.6246000007,..."
61,BARNSTABLE,20,35080,40949,47821,5869,6872,TC,1,NO,...,03635,25001005,1,109.812,0.172,45193,-2628,7299.700780,4.443901e+05,"POLYGON ((290001.7524999976 818233.8746000007,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,1,NO,...,78865,25021135,21,0.188,0.000,53743,-245,156.088379,7.597761e+02,"POLYGON ((246790.8125 888882.3746000007, 24679..."
427,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,1,NO,...,78865,25021135,21,5.065,0.008,53743,-245,932.123713,2.049563e+04,"POLYGON ((247384.8725000024 892443.1246000007,..."
979,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,1,NO,...,78865,25021135,21,1.635,0.003,53743,-245,360.366567,6.615137e+03,"POLYGON ((247440.5424999967 887133.9345999993,..."
98,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,0,NO,...,78865,25021135,21,11319.567,17.687,53743,-245,48895.208838,4.580870e+07,"POLYGON ((246455.5925000012 888926.8245999999,..."
1077,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,1,NO,...,78865,25021135,21,0.997,0.002,53743,-245,403.173568,4.035923e+03,"POLYGON ((248208.1325000003 890556.8145999983,..."
1105,WEYMOUTH,336,54273,54063,53988,-210,-75,TC,1,NO,...,78865,25021135,21,17.340,0.027,53743,-245,1391.881935,7.017090e+04,"POLYGON ((248357.012500003 891115.6246000007, ..."
1031,WHATELY,337,1363,1375,1573,12,198,T,0,NO,...,79110,25011130,11,13226.018,20.666,1496,-77,32807.468144,5.352382e+07,"POLYGON ((110734.0925000012 913490.5745999999,..."
212,WHITMAN,338,13684,13240,13882,-444,642,T,0,NO,...,79530,25023135,23,4453.393,6.958,14489,607,18499.964978,1.802225e+07,"POLYGON ((249442.8924999982 870782.1246000007,..."
834,WILBRAHAM,339,12166,12635,13473,469,838,T,0,NO,...,79740,25013115,13,14293.023,22.333,14219,746,36766.775406,5.784176e+07,"POLYGON ((126522.9324999973 878373.194600001, ..."
814,WILLIAMSBURG,340,2447,2515,2427,68,-88,T,0,NO,...,79915,25015095,15,16430.140,25.672,2482,55,36652.471517,6.649037e+07,"POLYGON ((103765.7424999997 907237.0645999983,..."
643,WILLIAMSTOWN,341,8383,8220,8424,-163,204,T,0,NO,...,79985,25003155,3,29986.518,46.854,7754,-670,46832.408706,1.213511e+08,"POLYGON ((63790.65250000358 945033.4246000014,..."
708,WILMINGTON,342,17442,17651,21367,209,3716,T,0,NO,...,80230,25017260,17,10971.272,17.143,22325,958,31733.734242,4.439912e+07,"POLYGON ((229921.5424999967 927676.4946000017,..."
680,WINCHENDON,343,7293,8805,9611,1512,806,T,0,NO,...,80405,25027295,27,28230.658,44.110,10300,689,42724.870251,1.142472e+08,"POLYGON ((149416.7424999997 930853.3245999999,..."
335,WINCHESTER,344,20021,20267,20810,246,543,T,0,YES,...,80510,25017265,17,135.862,0.212,21374,564,10746.266446,5.498122e+05,"POLYGON ((228813.4425000027 909999.9946000017,..."
1129,WINCHESTER,344,20021,20267,20810,246,543,T,0,NO,...,80510,25017265,17,3926.297,6.135,21374,564,28594.497133,1.588920e+07,"POLYGON ((231307.0625 911505.114599999, 231149..."
751,WINDSOR,345,589,770,875,181,105,T,0,NO,...,80685,25003160,3,22503.495,35.162,899,24,39079.472030,9.106836e+07,"POLYGON ((78513.6325000003 922282.8145999983, ..."
871,WINTHROP,346,18896,18127,18303,-769,176,TC,1,NO,...,80930,25025020,25,1.629,0.003,17497,-806,353.730043,6.592294e+03,"POLYGON ((242426.2824999988 901877.8746000007,..."
829,WINTHROP,346,18896,18127,18303,-769,176,TC,1,NO,...,80930,25025020,25,26.833,0.042,17497,-806,1448.125134,1.085886e+05,"POLYGON ((242853.1525000036 901631.6246000007,..."
524,WINTHROP,346,18896,18127,18303,-769,176,TC,1,NO,...,80930,25025020,25,0.405,0.001,17497,-806,294.314022,1.640764e+03,"POLYGON ((243869.5925000012 903174.1845999993,..."
589,WINTHROP,346,18896,18127,18303,-769,176,TC,0,NO,...,80930,25025020,25,235.458,0.368,17497,-806,4656.788906,9.528723e+05,"POLYGON ((241320.1325000003 902960.2545999996,..."
500,WINTHROP,346,18896,18127,18303,-769,176,TC,0,NO,...,80930,25025020,25,1192.995,1.864,17497,-806,20584.450378,4.827880e+06,"POLYGON ((242889.1424999982 904597.6246000007,..."
553,WOBURN,347,37251,35943,37258,-1308,1315,C,0,NO,...,81035,25017010,17,8283.535,12.943,38120,862,27522.346202,3.352227e+07,"POLYGON ((231254.4525000006 916708.7346000001,..."
667,WORCESTER,348,159843,169759,172648,9916,2889,C,0,NO,...,82000,25027030,27,24602.486,38.441,181045,8397,42619.276768,9.956271e+07,"POLYGON ((177883.3125 895676.4946000017, 17868..."
410,WORTHINGTON,349,1059,1156,1270,97,114,T,0,NO,...,82175,25015100,15,20545.945,32.103,1156,-114,45078.989129,8.314652e+07,"POLYGON ((86385.40250000358 910085.0645999983,..."
967,WRENTHAM,350,8191,9006,10554,815,1548,T,0,NO,...,82315,25021140,21,14465.195,22.602,10955,401,38486.891415,5.853862e+07,"POLYGON ((217782.5724999979 870243.0745999999,..."
997,YARMOUTH,351,19690,21174,24807,1484,3633,T,0,NO,...,82525,25001075,1,15942.189,24.910,23793,-1014,88389.432754,6.451574e+07,"POLYGON ((305686.1225000024 831682.1845999993,..."
123,YARMOUTH,351,19690,21174,24807,1484,3633,T,1,NO,...,82525,25001075,1,0.880,0.001,23793,-1014,263.052657,3.560275e+03,"POLYGON ((305918.0724999979 821572.3145999983,..."
453,YARMOUTH,351,19690,21174,24807,1484,3633,T,1,NO,...,82525,25001075,1,1.042,0.002,23793,-1014,262.737342,4.214666e+03,"POLYGON ((303452.0625 822639.2545999996, 30343..."
1110,YARMOUTH,351,19690,21174,24807,1484,3633,T,0,NO,...,82525,25001075,1,2.912,0.005,23793,-1014,936.459967,1.178420e+04,"POLYGON ((308631.5825000033 822826.5445999987,..."
503,YARMOUTH,351,19690,21174,24807,1484,3633,T,1,NO,...,82525,25001075,1,0.229,0.000,23793,-1014,127.706854,9.280658e+02,"POLYGON ((303929.8125 820790.4946000017, 30395..."

In [35]:
gdf2 = gdf.drop_duplicates(subset ="TOWN_ID", keep = 'first',inplace=False)

In [36]:
gdf2.shape

(351, 23)

In [37]:
mosdf = pd.read_csv("/Users/lbrown01/Dropbox/DataScienceStuff/Data/WNV_EE/formatMos.csv")

In [38]:
mosdf.head(5)

,Specimen_Type,Sample_ID,Species,Date,Town,State,County,Test_Type,Result,Submitted_for_Testing,DOY,Year
0,Mosquito,SL04-0001,Culiseta_melanura,2004-08-02,Easton,MA,Bristol,EEE,Positive,Yes,215,2004
1,Mosquito,SL04-0002,Culex_species,2004-08-04,Middleborough,MA,Plymouth,EEE,Positive,Yes,217,2004
2,Mosquito,SL04-0003,Culiseta_melanura,2004-08-04,Easton,MA,Bristol,EEE,Positive,Yes,217,2004
3,Mosquito,SL04-0004,Culiseta_melanura,2004-08-04,Easton,MA,Bristol,EEE,Positive,Yes,217,2004
4,Mosquito,SL04-0005,Culiseta_melanura,2004-08-05,Halifax,MA,Plymouth,EEE,Positive,Yes,218,2004

In [39]:
#make a new column for town to match town shapefile
mosdf['TOWN'] = mosdf['Town']

In [40]:
#capitalize all town names in the new column to match town shapefile
mosdf['TOWN'] = mosdf['TOWN'].str.upper()

In [41]:
mosdf.head(5)

,Specimen_Type,Sample_ID,Species,Date,Town,State,County,Test_Type,Result,Submitted_for_Testing,DOY,Year,TOWN
0,Mosquito,SL04-0001,Culiseta_melanura,2004-08-02,Easton,MA,Bristol,EEE,Positive,Yes,215,2004,EASTON
1,Mosquito,SL04-0002,Culex_species,2004-08-04,Middleborough,MA,Plymouth,EEE,Positive,Yes,217,2004,MIDDLEBOROUGH
2,Mosquito,SL04-0003,Culiseta_melanura,2004-08-04,Easton,MA,Bristol,EEE,Positive,Yes,217,2004,EASTON
3,Mosquito,SL04-0004,Culiseta_melanura,2004-08-04,Easton,MA,Bristol,EEE,Positive,Yes,217,2004,EASTON
4,Mosquito,SL04-0005,Culiseta_melanura,2004-08-05,Halifax,MA,Plymouth,EEE,Positive,Yes,218,2004,HALIFAX

In [42]:
mosdf2 = pd.merge(gdf2,mosdf,on="TOWN",how="right")

In [43]:
mosdf2.shape

(260300, 35)

In [44]:
mosdf2.head(5)

,TOWN,TOWN_ID,POP1980,POP1990,POP2000,POPCH80_90,POPCH90_00,TYPE,ISLAND,COASTAL_PO,...,Species,Date,Town,State,County,Test_Type,Result,Submitted_for_Testing,DOY,Year
0,HINGHAM,131.0,19942.0,19821.0,19882.0,-121.0,61.0,T,1.0,NO,...,Culiseta_melanura,2006-09-15,Hingham,MA,Plymouth,EEE,Positive,Yes,258,2006
1,HINGHAM,131.0,19942.0,19821.0,19882.0,-121.0,61.0,T,1.0,NO,...,Culiseta_melanura,2013-08-22,Hingham,MA,Plymouth,EEE,Positive,Yes,234,2013
2,HINGHAM,131.0,19942.0,19821.0,19882.0,-121.0,61.0,T,1.0,NO,...,Coquillettidia_perturbans,2013-08-22,Hingham,MA,Plymouth,EEE,Positive,Yes,234,2013
3,HINGHAM,131.0,19942.0,19821.0,19882.0,-121.0,61.0,T,1.0,NO,...,Culiseta_melanura,2013-08-22,Hingham,MA,Plymouth,WNv,Positive,Yes,234,2013
4,HINGHAM,131.0,19942.0,19821.0,19882.0,-121.0,61.0,T,1.0,NO,...,Aedes_vexans,2005-06-22,Hingham,MA,Plymouth,"EEE,_WNv",Negative,Yes,173,2005

In [25]:
#write to file
mosdf2.to_csv("/Users/lbrown01/Dropbox/DataScienceStuff/Data/WNV_EE/MosTowndat.csv", encoding='utf-8', index=False)

In [45]:
mosdf2.TOWN.unique()

array(['HINGHAM', 'QUINCY', 'WELLESLEY', 'MARSHFIELD', 'BROCKTON',
       'HANSON', 'MASHPEE', 'FALMOUTH', 'SCITUATE', 'HULL', 'SHREWSBURY',
       'STOCKBRIDGE', 'WESTHAMPTON', 'CHARLTON', 'SUTTON', 'EGREMONT',
       'FRANKLIN', 'NORFOLK', 'NORTHBRIDGE', 'STURBRIDGE', 'MEDWAY',
       'NORWELL', 'AUBURN', 'BOSTON', 'COHASSET', 'WEYMOUTH', 'DENNIS',
       'WESTPORT', 'DARTMOUTH', 'BARNSTABLE', 'CHATHAM', 'FAIRHAVEN',
       'BRIMFIELD', 'CHILMARK', 'NANTUCKET', 'LEOMINSTER', 'AQUINNAH',
       'EDGARTOWN', 'TISBURY', 'MILTON', 'YARMOUTH', 'BOURNE',
       'MATTAPOISETT', 'SOMERSET', 'WAREHAM', 'ORLEANS', 'SWANSEA',
       'METHUEN', 'NEWBURY', 'GROVELAND', 'NEWBURYPORT', 'OXFORD',
       'LITTLETON', 'BRIDGEWATER', 'MIDDLEBOROUGH', 'PROVINCETOWN',
       'DUXBURY', 'TRURO', 'WHITMAN', 'PEMBROKE', 'EASTHAM', 'REHOBOTH',
       'MARION', 'RICHMOND', 'BREWSTER', 'BERKLEY', 'FREETOWN',
       'SALISBURY', 'GLOUCESTER', 'DUDLEY', 'SPRINGFIELD', 'SANDISFIELD',
       'PLYMOUTH', 'DIGHTON', 'WELLFLEET', 'TAUNTON', 'ATTLEBORO',
       'NORTON', 'ROCHESTER', 'RAYNHAM', 'ROWE', 'ROWLEY', 'HATFIELD',
       'WINCHESTER', 'AVON', 'MILLBURY', 'OAKHAM', 'SALEM', 'WESTMINSTER',
       'IPSWICH', 'AMESBURY', 'MEDFORD', 'ESSEX', 'SANDWICH', 'SEEKONK',
       'FOXBOROUGH', 'HANOVER', 'MARBLEHEAD', 'SOUTHAMPTON', 'HARVARD',
       'LOWELL', 'LAKEVILLE', 'LYNN', 'WORTHINGTON', 'LINCOLN',
       'STONEHAM', 'NATICK', 'HAVERHILL', 'HAMPDEN', 'ROCKLAND',
       'HARWICH', 'TYRINGHAM', 'WARREN', 'SHEFFIELD', 'LANCASTER',
       'HUBBARDSTON', 'WESTFORD', 'HAMILTON', 'BOXBOROUGH', 'DALTON',
       'PEABODY', 'CARLISLE', 'BELLINGHAM', 'EASTHAMPTON', 'BEDFORD',
       'WINTHROP', 'BEVERLY', 'LAWRENCE', 'BECKET', 'WARE', 'BELCHERTOWN',
       'NORTHAMPTON', 'LEE', 'MELROSE', 'HANCOCK', 'ABINGTON', 'UPTON',
       'WOBURN', 'WAYLAND', 'LENOX', 'HADLEY', 'REVERE', 'MALDEN',
       'SWAMPSCOTT', 'HINSDALE', 'SUNDERLAND', 'NAHANT', 'ERVING',
       'MILLIS', 'RANDOLPH', 'LUDLOW', 'TEWKSBURY', 'HEATH',
       'WILLIAMSTOWN', 'EASTON', 'BRAINTREE', 'WORCESTER', 'TYNGSBOROUGH',
       'DUNSTABLE', 'BERNARDSTON', 'AYER', 'DEERFIELD', 'WENDELL',
       'WILMINGTON', 'MONTAGUE', 'TEMPLETON', 'GARDNER', 'SAUGUS',
       'DRACUT', 'ACTON', 'DANVERS', 'WINDSOR', 'LANESBOROUGH',
       'WASHINGTON', 'BOLTON', 'PITTSFIELD', 'GEORGETOWN', 'CLINTON',
       'HALIFAX', 'MEDFIELD', 'FRAMINGHAM', 'READING', 'ANDOVER',
       'SHELBURNE', 'WILBRAHAM', 'OTIS', 'BURLINGTON', 'HOLLISTON',
       'BROOKFIELD', 'HOPKINTON', 'SHERBORN', 'EVERETT', 'CHELSEA',
       'RUTLAND', 'STOW', 'SUDBURY', 'CHICOPEE', 'PHILLIPSTON', 'SPENCER',
       'ASHLAND', 'WENHAM', 'MARLBOROUGH', 'WESTFIELD', 'WAKEFIELD',
       'SOUTHBRIDGE', 'CHESHIRE', 'BOYLSTON', 'CARVER', 'MIDDLETON',
       'LONGMEADOW', 'LUNENBURG', 'CLARKSBURG', 'FITCHBURG', 'PELHAM',
       'BILLERICA', 'PLYMPTON', 'WEBSTER', 'WRENTHAM', 'HOLYOKE',
       'MAYNARD', 'HOLBROOK', 'KINGSTON', 'CONCORD', 'TOPSFIELD',
       'WHATELY', 'SOUTHBOROUGH', 'PLAINVILLE', 'STOUGHTON', 'STERLING',
       'MERRIMAC', 'ACUSHNET', 'ATHOL', 'GREENFIELD', 'NORTHBOROUGH',
       'CHELMSFORD', 'ARLINGTON', 'NEWTON', 'PRINCETON', 'LEICESTER',
       'MANSFIELD', 'CAMBRIDGE', 'COLRAIN', 'WESTBOROUGH', 'NEEDHAM',
       'WATERTOWN', 'WALTHAM', 'HOLDEN', 'SOUTHWICK', 'LEXINGTON',
       'BELMONT', 'DEDHAM', 'MILLVILLE', 'MILFORD', 'GRANBY',
       'SOMERVILLE', 'UXBRIDGE', 'MONSON', 'ADAMS', 'BARRE', 'ROYALSTON',
       'ORANGE', 'BLACKSTONE', 'DOUGLAS', 'GRAFTON', 'AGAWAM', 'WALES',
       'LYNNFIELD', 'DOVER', 'CANTON', 'NORWOOD', 'WESTWOOD', 'SHARON',
       'WALPOLE', 'MENDON', 'HUDSON', 'BERLIN', 'SHIRLEY', 'GROTON',
       'BROOKLINE', 'CHARLEMONT', 'PALMER', 'BOXFORD', 'WESTON',
       'AMHERST', 'PEPPERELL', 'HOPEDALE', 'NEW_BEDFORD',
       'EAST_BRIDGEWATER', 'WEST_BRIDGEWATER', 'FALL_RIVER',
       'NORTH_READING', 'EAST_BROOKFIELD', 'EAST_LONGMEADOW',
       'WEST_NEWBURY', 'MANCHESTER-BY-THE-SEA', 'NORTH_ANDOVER',
       'NORTH_ATTLEBOROUGH', 'NORTH_ADAMS', 'WEST_TISBURY', 'OAK_BLUFFS',
       'WEST_SPRINGFIELD', 'DEVENS', 'WEST_BOYLSTON', 'SOUTH_HADLEY',
       'GREAT_BARRINGTON', 'NEW_SALEM', 'NEW_MARLBOROUGH',
       'VINEYARD_HAVEN', 'WEST_BROOKFIELD', nan], dtype=object)

In [46]:
mosdf2.TOWN.nunique() #mosquitoes trapped in 309 of 351 towns in MA

309